// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AnimalShelter.Data;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterDbContext))]
    [Migration("20250902174209_UpdateToAnimalShelter")]
    partial class UpdateToAnimalShelter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            CategoryId = 1,
                            Description = "Ласкавий кіт, любить гратися з м'ячиками. Дуже дружелюбний до людей.",
                            Gender = "Самець",
                            ImageUrl = "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400",
                            Name = "Мурчик",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            CategoryId = 2,
                            Description = "Дружелюбний пес, добре ладнає з дітьми. Потребує активних прогулянок.",
                            Gender = "Самець",
                            ImageUrl = "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
                            Name = "Рекс",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            CategoryId = 3,
                            Description = "Маленький хомячок, дуже активний. Любить бігати в колесі.",
                            Gender = "Самка",
                            ImageUrl = "https://images.unsplash.com/photo-1516726817505-f5ed825624d8?w=400",
                            Name = "Хомка",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 4,
                            Age = 0,
                            CategoryId = 4,
                            Description = "Мишка-декоративна, дуже мила. Ідеально підходить для дітей.",
                            Gender = "Самка",
                            ImageUrl = "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400",
                            Name = "Мішка",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            CategoryId = 5,
                            Description = "Папуга, вміє говорити кілька слів. Дуже розумний і веселий.",
                            Gender = "Самець",
                            ImageUrl = "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
                            Name = "Кеша",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 6,
                            Age = 0,
                            CategoryId = 6,
                            Description = "Красиві золоті рибки для акваріуму. Потребують спеціального догляду.",
                            Gender = "Невідомо",
                            ImageUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400",
                            Name = "Золота рибка",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 7,
                            Age = 0,
                            CategoryId = 7,
                            Description = "Білий кролик, дуже пухнастий. Любить моркву та зелень.",
                            Gender = "Самка",
                            ImageUrl = "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=400",
                            Name = "Кролик Білий",
                            Status = "Доступний"
                        });
                });

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Коти"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Собаки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Хомяки"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Мишки"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Птахи"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Риби"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кролики"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Рептилії"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Інші"
                        });
                });

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Animal", b =>
                {
                    b.HasOne("Shop_mvc_pv421.Data.Entities.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
