// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AnimalShelter.Data;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterDbContext))]
    partial class AnimalShelterDbContext : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            CategoryId = 1,
                            Description = "Ласкавий кіт, любить гратися з м'ячиками. Дуже дружелюбний до людей.",
                            Gender = "Самець",
                            ImageUrl = "https://i.pinimg.com/736x/69/d4/f5/69d4f553a801270cc080e78402855353.jpg",
                            Name = "Мурчик",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            CategoryId = 2,
                            Description = "Дружелюбний пес, добре ладнає з дітьми. Потребує активних прогулянок.",
                            Gender = "Самець",
                            ImageUrl = "https://i.pinimg.com/736x/04/4d/b2/044db22d01a17a872b78b93f98d4b948.jpg",
                            Name = "Рекс",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            CategoryId = 3,
                            Description = "Маленький хомячок, дуже активний. Любить бігати в колесі.",
                            Gender = "Самка",
                            ImageUrl = "https://i.pinimg.com/736x/5e/ca/a9/5ecaa9e7ed0a5f4933d1a9ffccb78f9d.jpg",
                            Name = "Хомка",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 4,
                            Age = 0,
                            CategoryId = 4,
                            Description = "Мишка-декоративна, дуже мила. Ідеально підходить для дітей.",
                            Gender = "Самка",
                            ImageUrl = "https://i.pinimg.com/736x/fc/fb/97/fcfb97ed81a0c03ce4bfdfeb82870d7f.jpg",
                            Name = "Мішка",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            CategoryId = 5,
                            Description = "Папуга, вміє говорити кілька слів. Дуже розумний і веселий.",
                            Gender = "Самець",
                            ImageUrl = "https://i.pinimg.com/736x/7a/b2/45/7ab2455981b1a5caa622b4372da2988f.jpg",
                            Name = "Кеша",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 6,
                            Age = 0,
                            CategoryId = 6,
                            Description = "Красиві золоті рибки для акваріуму. Потребують спеціального догляду.",
                            Gender = "Невідомо",
                            ImageUrl = "https://i.pinimg.com/1200x/c8/65/33/c86533f9898ea801e4e47edac4fdc1f0.jpg",
                            Name = "Золота рибка",
                            Status = "Доступний"
                        },
                        new
                        {
                            Id = 7,
                            Age = 0,
                            CategoryId = 7,
                            Description = "Білий кролик, дуже пухнастий. Любить моркву та зелень.",
                            Gender = "Самка",
                            ImageUrl = "https://i.pinimg.com/736x/61/57/e8/6157e8486c7b0edd02f7c23e8e843dcd.jpg",
                            Name = "Кролик Білий",
                            Status = "Доступний"
                        });
                });

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Коти"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Собаки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Хомяки"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Мишки"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Птахи"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Риби"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кролики"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Рептилії"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Інші"
                        });
                });

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Animal", b =>
                {
                    b.HasOne("Shop_mvc_pv421.Data.Entities.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop_mvc_pv421.Data.Entities.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
